#!/usr/bin/bash
#                                  # -l is necessary to initialize modules correctly!
#SBATCH --ntasks=27                # All #SBATCH lines have to follow uninterrupted
#SBATCH --time=04:00:00            # comments start with # and do not count as interruptions
#SBATCH --job-name=sensitivity_events_over_line
#SBATCH --export=NONE              # do not export environment from submitting shell
                                   # first non-empty non-comment line ends SBATCH options
unset SLURM_EXPORT_ENV             # enable export of environment from this script to srun

source ~/.bashrc
source activate atmos_sci

# Specify the start and end years
yearStart=1940
yearEnd=2022

# line specs
lon="30"
latMin="-12"
latMax="5"

# Generate an array of years from yearStart to yearEnd
years=()
for (( year=yearStart; year<=yearEnd; year++ )); do
    years+=($year)
done

# Convert the array into a space-separated string
yearArgs="${years[@]}"

# Paths to locs unique to each parameter combination
dataSavePath1D="/home/atuin/c104fa/c104fa10/eeaWesterliesPaper/tcWesterlyDays/sensitivity/full/eventsLine1D." #$(printf "%02d" "$lon")E.$(printf "%02d" "$latMin")_$(printf "%02d" "$latMax")N.
dataSavePath2D="/home/atuin/c104fa/c104fa10/eeaWesterliesPaper/tcWesterlyDays/sensitivity/full/eventsLine2D." #$(printf "%02d" "$lon")E.$(printf "%02d" "$latMin")_$(printf "%02d" "$latMax")N.
westerlyPath="/home/atuin/c104fa/c104fa10/data/westerlies/sensitivity/mf700/"

# Log path
logDir="/home/atuin/c104fa/c104fa10/eeaWesterliesPaper/tcWesterlyDays/sensitivity/full/logs/"

# Define the parameters and their possible values
directionValues=(40 45 50)
magnitudePercentileValues=(60 70 80)
sizeValues=(750 1000 1500)

python_script="/home/atuin/c104fa/c104fa10/eeaWesterliesPaper/tcWesterlyDays/events_over_line.py"

# Run the code for each value combination
for direction in "${directionValues[@]}"; do
  for percentage in "${magnitudePercentileValues[@]}"; do
    for size in "${sizeValues[@]}"; do

        # Define input arguments
        dataSaveLoc1D="${dataSavePath1D}dir.${direction}_thresh.${percentage}_size.${size}.csv"
        dataSaveLoc2D="${dataSavePath2D}dir.${direction}_thresh.${percentage}_size.${size}.nc"
        westerlyLoc="${westerlyPath}/dir.${direction}_thresh.${percentage}_size.${size}/data/event."

        log_file="${logDir}/log_dir.${direction}_thresh.${percentage}_size.${size}.txt"

        nohup python3 $python_script --dataSaveLoc1D "$dataSaveLoc1D" --dataSaveLoc2D "$dataSaveLoc2D" --westerlyPath "$westerlyLoc" --years $yearArgs --lon $lon --latMin $latMin --latMax $latMax > "$log_file" 2>&1 &
    done
  done
done

# Wait for all background processes to finish
wait

echo "Sensitivity test completed."